name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip extension
        run: |
          cd src/extension
          zip -r ../../dpd-extension.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dpd-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate updates.xml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cat <<EOF > updates.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='pcfjbigbfcibglpegphbafmolhhkkmdh'>
              <updatecheck codebase='https://github.com/folgercn/dpd-api/releases/download/v$VERSION/dpd-extension.zip' version='$VERSION' />
            </app>
          </gupdate>
          EOF

      - name: Deploy updates.xml to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
